### ISSUE TITLE
Unsupport format character error when running

### ISSUE THREAD

**Issue by ChuckGl** [thorrak/tiltbridge_junior#3]
Getting the below error when running python3 -m tiltbridge_junior or pyhon3 tiltbridge_junior.py.  It also would not log to log/tiltbridge-jr.log

Traceback (most recent call last):
  File "/usr/lib/python3.9/logging/__init__.py", line 1079, in emit
    msg = self.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 923, in format
    return fmt.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 662, in format
    s = self.formatMessage(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 631, in formatMessage
    return self._style.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 430, in format
    return self._format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 426, in _format
    return self._fmt % record.__dict__
ValueError: unsupported format character ':' (0x3a) at index 24

To correct the issue:
Found if I change line 24:
     format='%(asctime)s %(levelname):-8s %(message)s', datefmt='%Y-%m-%d %H:%M:%S')
to (delete the ":" before -8s):
     format='%(asctime)s %(levelname)-8s %(message)s', datefmt='%Y-%m-%d %H:%M:%S')

**Comment by thorrak** [comment]
Huh -- Thank you for this. Sorry this went so long undetected!

I'll get this fix merged momentarily.
